"""The Sprite type and the blitter.

Sprites are authored as role grids - 'B' for body, 'W' for window - never as
literal colours. That is what lets one bus sprite render in whatever colour its
route is, and what lets a theme reinterpret every role at once.

The art itself lives in `art/sprites_data.py`, generated by tools/author_art.py.

Origin when blitting is the BOTTOM-left, because vehicles sit on a track line
and that is the edge that must stay put. Lamps sit on the right: everything
travels left-to-right toward its stop.
"""

from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class Sprite:
    width: int
    height: int
    rows: List[str]


def blit(draw, sprite, x, y, colours):
    """Draw `sprite` with its BOTTOM-left corner at (x, y).

    `colours` is a resolved role->RGB dict from Theme.role_colours(). Roles
    absent from it are skipped, which is how transparency works.
    """
    top = int(y) - sprite.height
    x = int(x)
    for ry, row in enumerate(sprite.rows):
        py = top + ry
        run_start, run_role = None, None
        for rx in range(sprite.width + 1):
            role = row[rx] if rx < sprite.width else None
            if role != run_role:
                if run_role in colours and run_start is not None:
                    draw.rectangle((x + run_start, py, x + rx - 1, py),
                                   fill=colours[run_role])
                run_start, run_role = rx, role
