# Builds railmap.py (the schematic map data the ESP32 loads) from the
# hand-laid schematic positions below + real station coordinates in
# stations.json (pulled from the AT GTFS API).
#
#   python tools/gen_railmap.py            -> writes railmap.py
import json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
REAL = json.load(open(os.path.join(HERE, "stations.json")))

# schematic pixel positions on the 320x240 screen
POS = {
    # City Rail Link
    "Waitemata": (204, 40), "Te Waihorotiu": (180, 40),
    "Karanga-a-Hape": (164, 56), "Maungawhau": (148, 72),
    # inner
    "Grafton": (180, 72), "Parnell": (204, 64), "Newmarket": (204, 88),
    # east
    "Orakei": (226, 40), "Meadowbank": (246, 40), "Glen Innes": (266, 48),
    "Panmure": (280, 62), "Sylvia Park": (280, 116),
    # south
    "Remuera": (214, 98), "Greenlane": (224, 108), "Ellerslie": (234, 118),
    "Penrose": (244, 128), "Otahuhu": (256, 140), "Middlemore": (256, 154),
    "Papatoetoe": (256, 166), "Puhinui": (256, 178), "Manukau": (270, 192),
    "Homai": (248, 186), "Manurewa": (240, 194), "Te Mahia": (232, 202),
    "Takaanini": (224, 210), "Papakura": (210, 210), "Drury": (196, 210),
    "Paerata": (182, 210), "Pukekohe": (168, 210),
    # Onehunga branch
    "Te Papapa": (232, 140), "Onehunga": (220, 152),
    # west
    "Kingsland": (140, 80), "Morningside": (132, 88), "Baldwin Ave": (124, 96),
    "Mt Albert": (116, 104), "Avondale": (108, 112), "New Lynn": (100, 120),
    "Fruitvale": (72, 120), "Glen Eden": (44, 120), "Sunnyvale": (32, 108),
    "Henderson": (20, 96), "Sturges Rd": (20, 82), "Ranui": (20, 68),
    "Swanson": (20, 54),
}

CRL = ("Waitemata", "Te Waihorotiu", "Karanga-a-Hape", "Maungawhau")

# name -> (label text, x, y)
LABELS = {
    "Swanson": ("Swanson", 28, 50),
    "Henderson": ("Henderson", 28, 92),
    "New Lynn": ("New Lynn", 72, 128),
    "Maungawhau": ("Maungawhau", 60, 68),
    "Karanga-a-Hape": ("K Rd", 126, 50),
    "Te Waihorotiu": ("Te Waihorotiu", 70, 34),
    "Waitemata": ("Waitemata", 186, 24),
    "Newmarket": ("Newmarket", 134, 96),
    "Otahuhu": ("Otahuhu", 264, 138),
    "Manukau": ("Manukau", 258, 200),
    "Pukekohe": ("Pukekohe", 144, 196),
    "Onehunga": ("Onehunga", 150, 148),
    "Papakura": ("Papakura", 194, 216),
}

# line id, colour, station order (from AT's longest trip patterns)
LINES = [
    ("E-W", (0x97, 0xC9, 0x3D), [
        "Swanson", "Ranui", "Sturges Rd", "Henderson", "Sunnyvale", "Glen Eden",
        "Fruitvale", "New Lynn", "Avondale", "Mt Albert", "Baldwin Ave",
        "Morningside", "Kingsland", "Maungawhau", "Karanga-a-Hape",
        "Te Waihorotiu", "Waitemata", "Orakei", "Meadowbank", "Glen Innes",
        "Panmure", "Sylvia Park", "Otahuhu", "Middlemore", "Papatoetoe",
        "Puhinui", "Manukau"]),
    ("S-C", (0xD5, 0x29, 0x23), [
        "Pukekohe", "Paerata", "Drury", "Papakura", "Takaanini", "Te Mahia",
        "Manurewa", "Homai", "Puhinui", "Papatoetoe", "Middlemore", "Otahuhu",
        "Penrose", "Ellerslie", "Greenlane", "Remuera", "Newmarket", "Grafton",
        "Karanga-a-Hape", "Te Waihorotiu", "Waitemata", "Parnell", "Newmarket"]),
    ("O-W", (0x00, 0xAE, 0xEF), [
        "Onehunga", "Te Papapa", "Penrose", "Ellerslie", "Greenlane", "Remuera",
        "Newmarket", "Grafton", "Maungawhau", "Kingsland", "Morningside",
        "Baldwin Ave", "Mt Albert", "Avondale", "New Lynn", "Fruitvale",
        "Glen Eden", "Sunnyvale", "Henderson"]),
]
GAP = 3   # px between parallel lines on shared track


def rgb565(c):
    r, g, b = c
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def build():
    # which lines use each piece of track
    users = {}
    for li, (_, _, seq) in enumerate(LINES):
        for a, b in zip(seq, seq[1:]):
            users.setdefault(frozenset((a, b)), []).append(li)
    segs = []
    for li, (_, col, seq) in enumerate(LINES):
        for a, b in zip(seq, seq[1:]):
            u = sorted(set(users[frozenset((a, b))]))
            # canonical direction so every line offsets to the same side
            p, q = sorted((a, b), key=lambda n: (POS[n][0], POS[n][1]))
            (x0, y0), (x1, y1) = POS[p], POS[q]
            dx, dy = x1 - x0, y1 - y0
            ln = math.hypot(dx, dy)
            nx, ny = -dy / ln, dx / ln
            off = (u.index(li) - (len(u) - 1) / 2) * GAP
            ox, oy = round(nx * off), round(ny * off)
            (la0, lo0), (la1, lo1) = REAL[p], REAL[q]
            segs.append((li, x0 + ox, y0 + oy, x1 + ox, y1 + oy,
                         round(la0, 5), round(lo0, 5), round(la1, 5), round(lo1, 5)))
    return segs


def main():
    segs = build()
    out = ["# generated by tools/gen_railmap.py -- do not edit",
           "LINES = %r" % [(n, rgb565(c)) for n, c, _ in LINES],
           "SEGS = ("]
    out += ["    %r," % (s,) for s in segs]
    out.append(")")
    out.append("STATIONS = (")
    for n, (x, y) in POS.items():
        out.append("    %r," % ((x, y, n in CRL),))
    out.append(")")
    out.append("LABELS = (")
    for n, (t, x, y) in LABELS.items():
        out.append("    %r," % ((t, x, y, n in CRL),))
    out.append(")")
    path = os.path.join(HERE, "..", "railmap.py")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote", os.path.normpath(path), len(segs), "segments")


if __name__ == "__main__":
    main()
